# Default initial positions for kmr_iiwa's ros2_control fake system

initial_positions:
  iiwa_joint_1: 0
  iiwa_joint_2: 0
  iiwa_joint_3: 0
  iiwa_joint_4: 0
  iiwa_joint_5: 0
  iiwa_joint_6: 0
  iiwa_joint_7: 0